const chat=document.getElementById('chat'),prompt=document.getElementById('prompt'),send=document.getElementById('sendBtn'),fileInput=document.getElementById('fileInput'),uploadBtn=document.getElementById('uploadBtn'),attachBtn=document.getElementById('attachBtn'),themeBtn=document.getElementById('themeBtn'),menuBtn=document.getElementById('menuBtn'),sidebar=document.querySelector('.sidebar'),libraryStatus=document.getElementById('libraryStatus');
const DB_NAME='elshori7y_ai',STORE='chunks';
function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function saveChunks(chunks){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction(STORE,'readwrite'),s=tx.objectStore(STORE);for(const c of chunks)s.put(c);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function allChunks(){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction(STORE,'readonly'),r=tx.objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function words(s){return [...new Set((s||'').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').split(/\s+/).filter(x=>x.length>1))]}
async function relevantContext(q){const chunks=await allChunks();if(!chunks.length)return '';const qw=words(q);const scored=chunks.map(c=>{const t=(c.text||'').toLowerCase();let score=0;for(const w of qw){if(t.includes(w))score+=w.length>4?3:1}return {...c,score}}).sort((a,b)=>b.score-a.score);const chosen=scored.filter(x=>x.score>0).slice(0,8);return chosen.map(x=>`[${x.book} — صفحة ${x.page}]\n${x.text}`).join('\n\n---\n\n').slice(0,18000)}
async function updateLibrary(){try{const c=await allChunks(),books=[...new Set(c.map(x=>x.book))];libraryStatus.textContent=books.length?`📚 ${books.length} كتاب محفوظ`:'لا توجد كتب مضافة'}catch{}}
function addMessage(text,type){const el=document.createElement('div');el.className='message '+type;el.textContent=text;chat.appendChild(el);chat.scrollTop=chat.scrollHeight;return el}
async function submit(text){text=(text||prompt.value).trim();if(!text)return;document.getElementById('welcome')?.remove();addMessage(text,'user');prompt.value='';send.disabled=true;const loading=addMessage('جاري البحث في كتبك والتفكير... 🤔','ai');try{const context=await relevantContext(text);const res=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:text,context})});let data;try{data=await res.json()}catch{throw new Error('الخادم أرسل استجابة غير صالحة.')}loading.remove();if(!res.ok)throw new Error(data?.error||'حدث خطأ');addMessage(data.text||'لم يصل رد من المساعد.','ai')}catch(err){loading.remove();addMessage('❌ '+(err.message||'تعذر الاتصال بالمساعد.'),'ai')}finally{send.disabled=false;prompt.focus()}}
async function indexPdf(file){if(!file||file.type!=='application/pdf')throw new Error('اختَر ملف PDF فقط.');if(!window.pdfjsLib)throw new Error('مكتبة PDF لم تُحمّل. تحقق من الإنترنت ثم أعد تحميل الصفحة.');pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const bytes=await file.arrayBuffer(),pdf=await pdfjsLib.getDocument({data:bytes}).promise,chunks=[];for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p),content=await page.getTextContent(),text=content.items.map(i=>i.str||'').join(' ').replace(/\s+/g,' ').trim();if(!text)continue;for(let start=0;start<text.length;start+=1200)chunks.push({id:`${file.name}:${p}:${start}`,book:file.name,page:p,text:text.slice(Math.max(0,start-120),start+1200)})}if(!chunks.length)throw new Error('الـPDF لا يحتوي نصًا قابلًا للقراءة. إذا كان عبارة عن صور، سنضيف OCR في المرحلة التالية.');await saveChunks(chunks);return{pages:pdf.numPages,chunks:chunks.length}}
async function handleFile(file){if(!file)return;document.getElementById('welcome')?.remove();addMessage('📚 '+file.name,'user');const loading=addMessage('جاري قراءة الكتاب وفهرسته على جهازك... ⏳','ai');fileInput.value='';try{const result=await indexPdf(file);loading.textContent=`✅ تم تجهيز الكتاب بالكامل: ${result.pages} صفحة، ${result.chunks} مقطع. اسألني عن محتواه الآن.`;await updateLibrary()}catch(e){loading.textContent='❌ تعذر تجهيز الملف: '+(e.message||'خطأ غير معروف')}}
send.addEventListener('click',()=>submit());prompt.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit()}});document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>submit(b.dataset.prompt)));uploadBtn.addEventListener('click',()=>fileInput.click());attachBtn.addEventListener('click',()=>fileInput.click());fileInput.addEventListener('change',()=>handleFile(fileInput.files[0]));themeBtn.addEventListener('click',()=>{document.body.classList.toggle('light');themeBtn.textContent=document.body.classList.contains('light')?'☀':'☾'});menuBtn.addEventListener('click',()=>sidebar.classList.toggle('open'));document.getElementById('newChat').addEventListener('click',()=>location.reload());updateLibrary();