(()=>{
const oldInput=document.getElementById('fileInput'),oldUpload=document.getElementById('uploadBtn'),oldAttach=document.getElementById('attachBtn');if(!oldInput||!oldUpload||!oldAttach)return;
const input=oldInput.cloneNode(true);oldInput.replaceWith(input);const upload=oldUpload.cloneNode(true);oldUpload.replaceWith(upload);const attach=oldAttach.cloneNode(true);oldAttach.replaceWith(attach);
const DB='elshori7y_ocr_jobs',STORE='jobs';
function jobDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function getJob(){const d=await jobDB();return new Promise((res,rej)=>{const r=d.transaction(STORE,'readonly').objectStore(STORE).get('current');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function putJob(job){const d=await jobDB();return new Promise((res,rej)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put(job);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function clearJob(){const d=await jobDB();return new Promise((res,rej)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).delete('current');tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
function status(msg){let el=document.getElementById('ocrStatus');if(!el){el=document.createElement('div');el.id='ocrStatus';el.className='library-status';document.querySelector('.side-section')?.appendChild(el)}el.textContent=msg}
async function ocrImage(source){const result=await Tesseract.recognize(source,'ara+eng');return(result.data.text||'').replace(/\s+/g,' ').trim()}
async function processPdf(file){pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;let job=await getJob();if(!job||job.name!==file.name||job.size!==file.size||job.total!==pdf.numPages){job={id:'current',name:file.name,size:file.size,total:pdf.numPages,nextPage:1,fileBlob:file};await putJob(job)}
for(let p=job.nextPage;p<=pdf.numPages;p++){status(`📖 قراءة الصفحة ${p} من ${pdf.numPages} — ${Math.round(p/pdf.numPages*100)}%`);const page=await pdf.getPage(p),content=await page.getTextContent();let text=content.items.map(i=>i.str||'').join(' ').replace(/\s+/g,' ').trim(),source='text';if(!text){status(`🔎 الصفحة ${p} من ${pdf.numPages} — OCR...`);const v=page.getViewport({scale:1.8}),canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');canvas.width=Math.ceil(v.width);canvas.height=Math.ceil(v.height);await page.render({canvasContext:ctx,viewport:v}).promise;text=await ocrImage(canvas);source='ocr';canvas.width=canvas.height=1}if(text){const chunks=[];for(let s=0;s<text.length;s+=1200)chunks.push({id:`${file.name}:${p}:${source}:${s}`,book:file.name,page:p,text:text.slice(Math.max(0,s-120),s+1200),source});await saveChunks(chunks)}job.nextPage=p+1;await putJob({...job,fileBlob:file})}
await clearJob();status(`✅ اكتمل الكتاب: ${pdf.numPages} صفحة — جاهز للـRAG`);await updateLibrary();document.getElementById('bookSelect').value=file.name}
async function processImage(file){status('🔎 جاري OCR للصورة...');const text=await ocrImage(file);if(!text)throw new Error('لم يتم العثور على نص واضح.');const chunks=[];for(let s=0;s<text.length;s+=1200)chunks.push({id:`${file.name}:image:${s}`,book:file.name,page:1,text:text.slice(Math.max(0,s-120),s+1200),source:'ocr'});await saveChunks(chunks);status('✅ تم تجهيز الصورة للـRAG');await updateLibrary();document.getElementById('bookSelect').value=file.name}
async function handle(file){if(!file)return;document.getElementById('welcome')?.remove();try{if(file.type==='application/pdf'||/\.pdf$/i.test(file.name))await processPdf(file);else await processImage(file)}catch(e){status('❌ '+(e.message||'تعذر تجهيز الملف'))}}
upload.onclick=()=>input.click();attach.onclick=()=>input.click();input.onchange=()=>{const f=input.files?.[0];input.value='';handle(f)};
(async()=>{const job=await getJob();if(job){const b=document.createElement('button');b.className='side-btn';b.id='resumeOCR';b.textContent=`▶️ استكمال ${job.name} — صفحة ${job.nextPage}/${job.total}`;document.querySelector('.sidebar')?.insertBefore(b,document.querySelector('.profile'));b.onclick=()=>processPdf(job.fileBlob).catch(e=>status('❌ '+(e.message||'تعذر الاستكمال')));status(`⏸️ يوجد كتاب غير مكتمل عند الصفحة ${job.nextPage} من ${job.total}`)}})();
})();