function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
async function chat(request,env){
 let body;try{body=await request.json()}catch{return json({error:'بيانات الطلب غير صالحة.'},400)}
 const message=typeof body?.message==='string'?body.message.trim():'';const context=typeof body?.context==='string'?body.context.trim():'';const mode=['books','general','auto'].includes(body?.mode)?body.mode:'auto';const instruction=typeof body?.instruction==='string'?body.instruction.trim():'';
 if(!message)return json({error:'اكتب رسالتك أولاً.'},400);if(message.length>12000)return json({error:'الرسالة طويلة جدًا.'},400);
 const apiKey=env?.GEMINI_API_KEY;if(typeof apiKey!=='string'||!apiKey.trim())return json({error:'لم يتم إعداد GEMINI_API_KEY على Cloudflare Worker.'},500);
 const bookBlock=context?`\n\nمقتطفات من كتب الطالب:\n${context}`:'';
 const prompt=`أنت Elshori7y AI، مساعد دراسي شخصي باللغة العربية. اشرح ببساطة وبشكل منظم، وساعد الطالب على الفهم بدل الحفظ فقط.\n\nوضع المعرفة الحالي: ${mode==='books'?'من الكتب فقط':mode==='general'?'المساعد العام':'تلقائي'}\nالتعليمات: ${instruction}${bookBlock}\n\nقواعد مهمة: ${mode==='books'?'اعتمد حصريًا على المقتطفات من كتب الطالب. إذا لم تجد الإجابة فيها، قل إن المعلومة غير موجودة في الكتب ولا تخمن.':mode==='general'?'أجب من معرفتك العامة، ولا تنسب المعلومات إلى كتب الطالب.':'استخدم مقتطفات الكتب كمصدر أول. إذا لم تكفِ للإجابة، يمكنك الاستعانة بمعرفتك العامة، ووضح للمستخدم أن الجزء الإضافي ليس من الكتاب.'}\nإذا استخدمت معلومة من مقتطفات الكتب، اذكر اسم الكتاب ورقم الصفحة عند الإمكان.\n\nرسالة الطالب:\n${message}`;
 let upstream;try{upstream=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent?key='+encodeURIComponent(apiKey.trim()),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}]})})}catch{return json({error:'تعذر الاتصال بخدمة Gemini.'},502)}
 let data;try{data=await upstream.json()}catch{return json({error:'Gemini أرسل استجابة غير صالحة.'},502)}
 if(!upstream.ok)return json({error:data?.error?.message||'حدث خطأ من Gemini.'},upstream.status);
 const text=data?.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'لم يصل رد من المساعد.';return json({text})
}
function esc(s){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function diagramSvg(spec,style){
 const title=String(spec?.title||'صورة تعليمية').slice(0,80),central=String(spec?.central||title).slice(0,80);const nodes=Array.isArray(spec?.nodes)?spec.nodes.map(x=>String(x||'').trim()).filter(Boolean).slice(0,8):[];const edges=Array.isArray(spec?.edges)?spec.edges.slice(0,12):[];const note=String(spec?.note||'').slice(0,180);const h=hash(title+central+nodes.join('|'));const bg=['#e8f1ff','#eafaf1','#fff3d9','#f5ecff'][h%4];const cx=600,cy=430,r=270;let lines='',boxes='';
 const pos=nodes.map((label,i)=>{const a=(Math.PI*2*i/Math.max(nodes.length,1))-Math.PI/2;return{x:cx+Math.cos(a)*r,y:cy+Math.sin(a)*r,label}});
 pos.forEach((p,i)=>{const a=(Math.PI*2*i/Math.max(nodes.length,1))-Math.PI/2;const q={x:cx+Math.cos(a)*r,y:cy+Math.sin(a)*r};lines+=`<line x1="${cx}" y1="${cy}" x2="${q.x}" y2="${q.y}" stroke="#64748b" stroke-width="4" marker-end="url(#arrow)"/>`;boxes+=`<g><rect x="${q.x-135}" y="${q.y-48}" width="270" height="96" rx="22" fill="white" stroke="#334155" stroke-width="3"/><text x="${q.x}" y="${q.y+8}" text-anchor="middle" direction="rtl" unicode-bidi="plaintext" font-family="Noto Sans Arabic,Arial,sans-serif" font-size="23" fill="#0f172a">${esc(p.label.slice(0,42))}</text></g>`});
 if(!nodes.length)boxes=`<rect x="465" y="382" width="270" height="96" rx="22" fill="white" stroke="#334155" stroke-width="3"/><text x="600" y="440" text-anchor="middle" direction="rtl" unicode-bidi="plaintext" font-family="Noto Sans Arabic,Arial,sans-serif" font-size="23" fill="#0f172a">${esc(central)}</text>`;
 return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="850" viewBox="0 0 1200 850"><defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${bg}"/><stop offset="1" stop-color="#fff"/></linearGradient><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#64748b"/></marker></defs><rect width="1200" height="850" rx="30" fill="url(#bg)"/><text x="600" y="70" text-anchor="middle" direction="rtl" unicode-bidi="plaintext" font-family="Noto Sans Arabic,Arial,sans-serif" font-size="36" font-weight="700" fill="#0f172a">${esc(title)}</text><text x="600" y="105" text-anchor="middle" direction="rtl" unicode-bidi="plaintext" font-family="Noto Sans Arabic,Arial,sans-serif" font-size="17" fill="#475569">${esc(style||'شرح درس')}</text><circle cx="600" cy="430" r="88" fill="#0f172a"/><text x="600" y="438" text-anchor="middle" direction="rtl" unicode-bidi="plaintext" font-family="Noto Sans Arabic,Arial,sans-serif" font-size="24" font-weight="700" fill="white">${esc(central)}</text>${lines}${boxes}${note?`<rect x="160" y="730" width="880" height="64" rx="18" fill="rgba(255,255,255,.82)"/><text x="600" y="770" text-anchor="middle" direction="rtl" unicode-bidi="plaintext" font-family="Noto Sans Arabic,Arial,sans-serif" font-size="18" fill="#334155">${esc(note)}</text>`:''}</svg>`
}
async function image(request,env){
 let body;try{body=await request.json()}catch{return json({error:'بيانات طلب الصورة غير صالحة.'},400)}
 const prompt=typeof body?.prompt==='string'?body.prompt.trim():'';const style=typeof body?.style==='string'?body.style.trim():'خريطة مفاهيم';const context=typeof body?.context==='string'?body.context.trim():'';
 if(!prompt)return json({error:'اكتب وصف الصورة أولًا.'},400);
 const apiKey=env?.GEMINI_API_KEY;if(typeof apiKey!=='string'||!apiKey.trim())return json({error:'لم يتم إعداد GEMINI_API_KEY على Cloudflare Worker.'},500);
 if(!context)return json({error:'لم يتم العثور على محتوى مناسب من الكتاب. اختر الكتاب الصحيح أو ابحث عن درس/موضوع موجود في الكتاب.'},400);
 const planner=`أنت مصمم صور تعليمية لمساعد دراسي. استخدم فقط المعلومات الموجودة في مقتطفات الكتاب أدناه، ولا تضف معلومات من خارجها. طلب الطالب: ${prompt}. نوع الرسم: ${style}.\n\nمقتطفات الكتاب:\n${context.slice(0,18000)}\n\nأخرج JSON فقط بلا Markdown بهذا الشكل: {"title":"عنوان قصير","central":"الفكرة الرئيسية","nodes":["عنصر1","عنصر2"],"edges":[{"from":"عنصر1","to":"عنصر2"}],"note":"خلاصة قصيرة"}. اختر من 3 إلى 8 عناصر مهمة فعلًا من النص. اجعل النصوص عربية قصيرة وواضحة. لا تخترع أسماء أو أرقام أو علاقات غير موجودة في المقتطفات.`;
 let upstream;try{upstream=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent?key='+encodeURIComponent(apiKey.trim()),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:planner}]}],generationConfig:{temperature:0.2,responseMimeType:'application/json'}})})}catch{return json({error:'تعذر الاتصال بـGemini لتحليل محتوى الكتاب.'},502)}
 let data;try{data=await upstream.json()}catch{return json({error:'Gemini أرسل استجابة غير صالحة.'},502)}
 if(!upstream.ok)return json({error:data?.error?.message||'حدث خطأ أثناء تحليل محتوى الكتاب.'},upstream.status);
 const raw=data?.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'';let spec;try{spec=JSON.parse(raw.replace(/^```json\s*/,'').replace(/\s*```$/,''))}catch{return json({error:'تعذر تحويل تحليل الكتاب إلى مخطط تعليمي.'},502)}
 const svg=diagramSvg(spec,style);return json({image:`data:image/svg+xml;base64,${btoa(unescape(encodeURIComponent(svg)))}`,format:'svg',labels:[],provider:'gemini-rag-svg',source:'book-rag'});
}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/api/chat'&&request.method==='POST')return chat(request,env);if(url.pathname==='/api/image'&&request.method==='POST')return image(request,env);if(url.pathname==='/api/health')return json({ok:true,secretConfigured:typeof env?.GEMINI_API_KEY==='string'&&env.GEMINI_API_KEY.length>0,hfConfigured:typeof env?.HF_TOKEN==='string'&&env.HF_TOKEN.length>0,bindingNames:Object.keys(env||{})});return env.ASSETS.fetch(request)}};