function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
async function chat(request,env){
 let body;try{body=await request.json()}catch{return json({error:'بيانات الطلب غير صالحة.'},400)}
 const message=typeof body?.message==='string'?body.message.trim():'';const context=typeof body?.context==='string'?body.context.trim():'';const mode=['books','general','auto'].includes(body?.mode)?body.mode:'auto';const instruction=typeof body?.instruction==='string'?body.instruction.trim():'';
 if(!message)return json({error:'اكتب رسالتك أولاً.'},400);if(message.length>12000)return json({error:'الرسالة طويلة جدًا.'},400);
 const apiKey=env?.GEMINI_API_KEY;if(typeof apiKey!=='string'||!apiKey.trim())return json({error:'لم يتم إعداد GEMINI_API_KEY على Cloudflare Worker.'},500);
 const bookBlock=context?`\n\nمقتطفات من كتب الطالب:\n${context}`:'';
 const prompt=`أنت Elshori7y AI، مساعد دراسي شخصي باللغة العربية. اشرح ببساطة وبشكل منظم، وساعد الطالب على الفهم بدل الحفظ فقط.\n\nوضع المعرفة الحالي: ${mode==='books'?'من الكتب فقط':mode==='general'?'المساعد العام':'تلقائي'}\nالتعليمات: ${instruction}${bookBlock}\n\nقواعد مهمة: ${mode==='books'?'اعتمد حصريًا على المقتطفات من كتب الطالب. إذا لم تجد الإجابة فيها، قل إن المعلومة غير موجودة في الكتب ولا تخمن.':mode==='general'?'أجب من معرفتك العامة، ولا تنسب المعلومات إلى كتب الطالب.':'استخدم مقتطفات الكتب كمصدر أول. إذا لم تكفِ للإجابة، يمكنك الاستعانة بمعرفتك العامة، ووضح للمستخدم أن الجزء الإضافي ليس من الكتاب.'}\nإذا استخدمت معلومة من مقتطفات الكتب، اذكر اسم الكتاب ورقم الصفحة عند الإمكان.\n\nرسالة الطالب:\n${message}`;
 let upstream;try{upstream=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent?key='+encodeURIComponent(apiKey.trim()),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}]})})}catch{return json({error:'تعذر الاتصال بخدمة Gemini.'},502)}
 let data;try{data=await upstream.json()}catch{return json({error:'Gemini أرسل استجابة غير صالحة.'},502)}
 if(!upstream.ok)return json({error:data?.error?.message||'حدث خطأ من Gemini.'},upstream.status);
 const text=data?.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'لم يصل رد من المساعد.';return json({text})
}
function esc(s){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;')}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function text(x,attrs){return `<text direction="rtl" unicode-bidi="plaintext" font-family="Noto Sans Arabic,Arial,sans-serif" ${attrs}>${esc(x)}</text>`}
function diagramSvg(spec,style){
 const title=String(spec?.title||'صورة تعليمية').slice(0,80),central=String(spec?.central||title).slice(0,80);const nodes=Array.isArray(spec?.nodes)?spec.nodes.map(x=>String(x||'').trim()).filter(Boolean).slice(0,8):[];const edges=Array.isArray(spec?.edges)?spec.edges.slice(0,12):[];const note=String(spec?.note||'').slice(0,180);const type=['mindmap','steps','comparison','timeline','science','classification'].includes(spec?.type)?spec.type:'mindmap';const h=hash(title+central+nodes.join('|'));const bg=['#e8f1ff','#eafaf1','#fff3d9','#f5ecff'][h%4];const W=1200,H=850;
 let body='';
 if(type==='steps'){
  const arr=nodes.slice(0,6);const gap=arr.length?1000/arr.length:1000;arr.forEach((label,i)=>{const x=100+i*gap;body+=`<g><rect x="${x}" y="300" width="${Math.min(180,gap-24)}" height="120" rx="24" fill="white" stroke="#334155" stroke-width="3"/>${text(String(i+1),`x="${x+35}" y="345" text-anchor="middle" font-size="26" font-weight="700" fill="#2563eb"`)}${text(label.slice(0,38),`x="${x+Math.min(180,gap-24)/2}" y="385" text-anchor="middle" font-size="19" fill="#0f172a"`)}</g>`;if(i<arr.length-1)body+=`<line x1="${x+Math.min(180,gap-24)}" y1="360" x2="${x+gap-8}" y2="360" stroke="#64748b" stroke-width="5" marker-end="url(#arrow)"/>`});
 }else if(type==='comparison'){
  const mid=Math.ceil(nodes.length/2),left=nodes.slice(0,mid),right=nodes.slice(mid);body+=`<rect x="70" y="180" width="500" height="500" rx="30" fill="white" stroke="#334155" stroke-width="3"/><rect x="630" y="180" width="500" height="500" rx="30" fill="white" stroke="#334155" stroke-width="3"/>`;body+=text(left[0]||'الأول',`x="320" y="240" text-anchor="middle" font-size="30" font-weight="700" fill="#0f172a"`)+text(right[0]||'الثاني',`x="880" y="240" text-anchor="middle" font-size="30" font-weight="700" fill="#0f172a"`);left.slice(1).forEach((v,i)=>body+=text('• '+v.slice(0,38),`x="320" y="${300+i*55}" text-anchor="middle" font-size="20" fill="#334155"`));right.slice(1).forEach((v,i)=>body+=text('• '+v.slice(0,38),`x="880" y="${300+i*55}" text-anchor="middle" font-size="20" fill="#334155"`));
 }else if(type==='timeline'){
  const arr=nodes.slice(0,7);body+=`<line x1="120" y1="440" x2="1080" y2="440" stroke="#64748b" stroke-width="7"/>`;arr.forEach((v,i)=>{const x=130+i*(940/Math.max(1,arr.length-1));body+=`<circle cx="${x}" cy="440" r="18" fill="#0f172a"/>`+text(String(v).slice(0,32),`x="${x}" y="${i%2?510:365}" text-anchor="middle" font-size="19" fill="#0f172a"`) });
 }else if(type==='science'){
  const arr=nodes.slice(0,6);body+=`<circle cx="600" cy="430" r="150" fill="white" stroke="#334155" stroke-width="4"/>`;arr.forEach((v,i)=>{const a=(Math.PI*2*i/Math.max(1,arr.length))-Math.PI/2,x=600+Math.cos(a)*350,y=430+Math.sin(a)*250;body+=`<line x1="600" y1="430" x2="${x}" y2="${y}" stroke="#64748b" stroke-width="4" marker-end="url(#arrow)"/>`+`<rect x="${x-120}" y="${y-42}" width="240" height="84" rx="20" fill="white" stroke="#334155" stroke-width="3"/>`+text(v.slice(0,36),`x="${x}" y="${y+7}" text-anchor="middle" font-size="20" fill="#0f172a"`) });body+=text(central,`x="600" y="438" text-anchor="middle" font-size="25" font-weight="700" fill="#0f172a"`);
 }else if(type==='classification'){
  const arr=nodes.slice(0,8);body+=`<rect x="450" y="150" width="300" height="100" rx="24" fill="#0f172a"/>`+text(central,`x="600" y="212" text-anchor="middle" font-size="24" font-weight="700" fill="white"`);arr.forEach((v,i)=>{const x=100+(i%4)*270,y=360+Math.floor(i/4)*190;body+=`<line x1="600" y1="250" x2="${x+120}" y2="${y}" stroke="#64748b" stroke-width="4" marker-end="url(#arrow)"/><rect x="${x}" y="${y}" width="240" height="100" rx="22" fill="white" stroke="#334155" stroke-width="3"/>`+text(v.slice(0,38),`x="${x+120}" y="${y+60}" text-anchor="middle" font-size="19" fill="#0f172a"`) });
 }else{
  const r=270;nodes.forEach((label,i)=>{const a=(Math.PI*2*i/Math.max(nodes.length,1))-Math.PI/2,x=600+Math.cos(a)*r,y=430+Math.sin(a)*r;body+=`<line x1="600" y1="430" x2="${x}" y2="${y}" stroke="#64748b" stroke-width="4" marker-end="url(#arrow)"/><rect x="${x-135}" y="${y-48}" width="270" height="96" rx="22" fill="white" stroke="#334155" stroke-width="3"/>`+text(label.slice(0,42),`x="${x}" y="${y+8}" text-anchor="middle" font-size="21" fill="#0f172a"`) });body+=`<circle cx="600" cy="430" r="88" fill="#0f172a"/>`+text(central,`x="600" y="438" text-anchor="middle" font-size="24" font-weight="700" fill="white"`);
 }
 return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${bg}"/><stop offset="1" stop-color="#fff"/></linearGradient><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#64748b"/></marker></defs><rect width="${W}" height="${H}" rx="30" fill="url(#bg)"/>${text(title,`x="600" y="70" text-anchor="middle" font-size="36" font-weight="700" fill="#0f172a"`)}${text(spec?.typeLabel||style||'شرح درس',`x="600" y="105" text-anchor="middle" font-size="17" fill="#475569"`)}${body}${note?`<rect x="160" y="730" width="880" height="64" rx="18" fill="rgba(255,255,255,.82)"/>${text(note,`x="600" y="770" text-anchor="middle" font-size="18" fill="#334155"`)}`:''}</svg>`
 }
async function image(request,env){
 let body;try{body=await request.json()}catch{return json({error:'بيانات طلب الصورة غير صالحة.'},400)}
 const prompt=typeof body?.prompt==='string'?body.prompt.trim():'';const requestedStyle=typeof body?.style==='string'?body.style.trim():'';const context=typeof body?.context==='string'?body.context.trim():'';
 if(!prompt)return json({error:'اكتب وصف الصورة أولًا.'},400);
 const apiKey=env?.GEMINI_API_KEY;if(typeof apiKey!=='string'||!apiKey.trim())return json({error:'لم يتم إعداد GEMINI_API_KEY على Cloudflare Worker.'},500);
 if(!context)return json({error:'لم يتم العثور على محتوى مناسب من الكتاب. اختر الكتاب الصحيح أو ابحث عن درس/موضوع موجود في الكتاب.'},400);
 const planner=`أنت مصمم صور تعليمية لمساعد دراسي. اقرأ مقتطفات الكتاب أولًا ثم اختر تلقائيًا أفضل نوع رسم لشرح المحتوى. لا تستخدم أي معلومة من خارج المقتطفات. طلب الطالب: ${prompt}. نوع الرسم الذي طلبه المستخدم إن وُجد: ${requestedStyle||'اختيار تلقائي'}.
الأنواع المتاحة: mindmap=خريطة ذهنية/مفاهيم، steps=خطوات أو عملية، comparison=مقارنة بين شيئين، timeline=خط زمني، science=مخطط علمي/علاقات، classification=تصنيف أو شجرة.
إذا لم يحدد المستخدم نوعًا، اختر النوع الأنسب بناءً على طبيعة المحتوى. أخرج JSON فقط بلا Markdown بهذا الشكل: {"type":"mindmap|steps|comparison|timeline|science|classification","typeLabel":"اسم النوع بالعربية","title":"عنوان قصير","central":"الفكرة الرئيسية","nodes":["عنصر1","عنصر2"],"edges":[{"from":"عنصر1","to":"عنصر2"}],"note":"خلاصة قصيرة"}. اختر 3 إلى 8 عناصر مهمة فعلًا من النص. في المقارنة اجعل أول عنصرين عنواني الطرفين ثم باقي العناصر نقاطًا. في الخطوات رتّب العناصر حسب تسلسلها في النص. اجعل النصوص عربية قصيرة وواضحة. لا تخترع أسماء أو أرقام أو علاقات غير موجودة في المقتطفات.

مقتطفات الكتاب:
${context.slice(0,18000)}`;
 let upstream;try{upstream=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent?key='+encodeURIComponent(apiKey.trim()),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:planner}]}],generationConfig:{temperature:0.2,responseMimeType:'application/json'}})})}catch{return json({error:'تعذر الاتصال بـGemini لتحليل محتوى الكتاب.'},502)}
 let data;try{data=await upstream.json()}catch{return json({error:'Gemini أرسل استجابة غير صالحة.'},502)}
 if(!upstream.ok)return json({error:data?.error?.message||'حدث خطأ أثناء تحليل محتوى الكتاب.'},upstream.status);
 const raw=data?.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'';let spec;try{spec=JSON.parse(raw.replace(/^```json\s*/,'').replace(/\s*```$/,''))}catch{return json({error:'تعذر تحويل تحليل الكتاب إلى مخطط تعليمي.'},502)}
 const svg=diagramSvg(spec,spec.typeLabel||requestedStyle||'شرح الدرس');return json({image:`data:image/svg+xml;base64,${btoa(unescape(encodeURIComponent(svg)))}`,format:'svg',labels:[],provider:'gemini-rag-svg',source:'book-rag',visualType:spec.type,typeLabel:spec.typeLabel||''});
}

function tgApi(env,method,payload){const token=env?.TELEGRAM_BOT_TOKEN;return fetch(`https://api.telegram.org/bot${encodeURIComponent(token)}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)})}
const tgCacheKey=chatId=>new Request(`https://cache.elshori7y.local/telegram-book/${chatId}`);
async function tgSend(env,chat_id,text){return tgApi(env,'sendMessage',{chat_id,text,disable_web_page_preview:true})}
async function tgGetFile(env,file_id){const r=await tgApi(env,'getFile',{file_id});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d?.description||'تعذر الحصول على ملف Telegram');return d.result}
async function tgDownload(env,file_path){const token=env.TELEGRAM_BOT_TOKEN;const r=await fetch(`https://api.telegram.org/file/bot${encodeURIComponent(token)}/${file_path}`);if(!r.ok)throw new Error('تعذر تنزيل الملف من Telegram');return r}
async function tgBookFor(chatId){return caches.default.match(tgCacheKey(chatId))}
async function tgStoreBook(chatId,response,meta){const headers=new Headers(response.headers);headers.set('x-telegram-book-name',meta.name||'كتاب');headers.set('x-telegram-book-type',meta.type||'application/pdf');headers.set('cache-control','public, max-age=86400');const body=await response.arrayBuffer();await caches.default.put(tgCacheKey(chatId),new Response(body,{headers}));return body.byteLength}
async function tgAskBook(env,chatId,question){const cached=await tgBookFor(chatId);if(!cached)return '📚 ابعتلي الكتاب الأول كـ PDF أو صورة، وبعدها اسألني عنه.';const type=cached.headers.get('x-telegram-book-type')||'application/pdf';const name=cached.headers.get('x-telegram-book-name')||'الكتاب';const bytes=new Uint8Array(await cached.arrayBuffer());if(bytes.byteLength>19000000)return '⚠️ الملف أكبر من الحد المناسب للقراءة المباشرة. ابعت نسخة PDF أصغر.';let binary='';const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)binary+=String.fromCharCode(...bytes.subarray(i,Math.min(i+chunk,bytes.length)));const b64=btoa(binary);const apiKey=env.GEMINI_API_KEY;if(!apiKey)return 'لم يتم إعداد GEMINI_API_KEY على Worker.';const prompt=`أنت مدرس Elshori7y على Telegram. أجب باللغة العربية ومن محتوى الكتاب المرفق فقط. إذا لم تجد الإجابة في الكتاب قل بوضوح إنها غير موجودة ولا تخمن. اذكر الصفحة إن استطعت. اسم الكتاب: ${name}. سؤال الطالب: ${question}`;const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent?key='+encodeURIComponent(apiKey.trim()),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt},{inlineData:{mimeType:type,data:b64}}]}]})});let d;try{d=await r.json()}catch{return 'Gemini أرسل استجابة غير صالحة.'}if(!r.ok)return d?.error?.message||'حدث خطأ من Gemini.';return d?.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'لم يصل رد من المساعد.'}
async function telegram(request,env){const token=env?.TELEGRAM_BOT_TOKEN;if(!token)return json({error:'لم يتم إعداد TELEGRAM_BOT_TOKEN على Cloudflare Worker.'},500);let update;try{update=await request.json()}catch{return json({ok:true})}const msg=update?.message;if(!msg?.chat?.id)return json({ok:true});const chatId=msg.chat.id;try{if(msg.document?.file_id){const f=await tgGetFile(env,msg.document.file_id);const r=await tgDownload(env,f.file_path);const type=msg.document.mime_type||'application/pdf';const name=msg.document.file_name||'كتاب';const size=await tgStoreBook(chatId,r,{name,type});await tgSend(env,chatId,`✅ استلمت «${name}» وحفظته مؤقتًا للمحادثة.\nالحجم: ${Math.round(size/1024/1024*10)/10} MB\n\nدلوقتي اسألني أي سؤال عن الكتاب.`);return json({ok:true})}if(msg.photo?.length){const photo=msg.photo[msg.photo.length-1];const f=await tgGetFile(env,photo.file_id);const r=await tgDownload(env,f.file_path);await tgStoreBook(chatId,r,{name:'صورة من الكتاب',type:'image/jpeg'});await tgSend(env,chatId,'✅ استلمت صورة الصفحة. اسألني عنها أو ابعت باقي الصفحات.');return json({ok:true})}const question=typeof msg.text==='string'?msg.text.trim():'';if(question==='/start'){await tgSend(env,chatId,'👋 أنا مدرس Elshori7y.\n\n📚 ابعتلي PDF أو صور صفحات الكتاب، وبعدها اسألني عنه.\n\nمثال: «اشرح الدرس الثالث» أو «ما أسباب كذا في الكتاب؟»');return json({ok:true})}if(question){await tgSend(env,chatId,'🧠 بقرأ الكتاب وبجهز الإجابة...');const answer=await tgAskBook(env,chatId,question);for(let i=0;i<answer.length;i+=3900)await tgSend(env,chatId,answer.slice(i,i+3900));}return json({ok:true})}catch(e){await tgSend(env,chatId,'❌ حصل خطأ: '+(e?.message||'تعذر معالجة الطلب.'));return json({ok:true})}}
async function telegramSetup(request,env){const token=env?.TELEGRAM_BOT_TOKEN;if(!token)return json({ok:false,error:'TELEGRAM_BOT_TOKEN غير موجود.'},500);const url=new URL(request.url);const webhook=new URL('/api/telegram/webhook',url.origin).href;const r=await tgApi(env,'setWebhook',{url:webhook,drop_pending_updates:true});let d;try{d=await r.json()}catch{d={ok:false,error:'استجابة Telegram غير صالحة'}}return json({webhook,telegram:d})}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/api/chat'&&request.method==='POST')return chat(request,env);if(url.pathname==='/api/image'&&request.method==='POST')return image(request,env);if(url.pathname==='/api/telegram/webhook'&&request.method==='POST')return telegram(request,env);if(url.pathname==='/api/telegram/setup'&&request.method==='GET')return telegramSetup(request,env);if(url.pathname==='/api/health')return json({ok:true,secretConfigured:typeof env?.GEMINI_API_KEY==='string'&&env.GEMINI_API_KEY.length>0,hfConfigured:typeof env?.HF_TOKEN==='string'&&env.HF_TOKEN.length>0,telegramConfigured:typeof env?.TELEGRAM_BOT_TOKEN==='string'&&env.TELEGRAM_BOT_TOKEN.length>0,bindingNames:Object.keys(env||{})});return env.ASSETS.fetch(request)}};